trigger:
- api-tests
 
# variables:
  #system.debug: true
  #disable.coverage.autogenerate: true

pool:
  vmImage: 'ubuntu-latest'
 
steps:

- script: >-
    echo "##vso[task.prependpath]$HOME/.dotnet/tools"

- script: >-
    dotnet tool install -g dotnet-reportgenerator-globaltool

- script: >-
    sh Code/codecoverage.sh 'Code/Avalanche.Api.Tests/Avalanche.Api.Tests.csproj' 'release' './TestResults/api'
    sh Code/codecoverage.sh 'Code/Avalanche.Security.Server.Tests/Avalanche.Security.Server.Tests.csproj' 'release' './TestResults/security'