name: $(BuildNumberPrefix)-push-docker-image-$(MajorVersion).$(MinorVersion).$(Patch).$(ReleaseStage)_$(MajorVersion).$(MinorVersion).$(Date:yyMM).$(Date:dd)$(Rev:rr)_$(Date:yyyyMMdd)T$(Date:hhmmss)

trigger:
  - dev
  
resources:
  repositories:
  - repository: devops
    type: git
    name: devops
    ref: dev

#pool:
  #vmImage: $(PoolVmImage)

pool: $(pool)

variables:
  
  - group: 'vg-dev-avalanche-api'
  
  #- name: System.Debug
    #value: true
  
stages:

# stage for creating PR comments if nuget pkgs verssion are not up to date
- template: pipeline\templates\nuget-version-check.yml@devops

- stage: build

  jobs:

  - job: build_test_publish
    steps:
     
     - checkout: self
     - checkout: devops

     - task: PowerShell@2
       displayName: List environmental variables
       inputs:
        targetType: 'inline'
        script: 'Get-ChildItem -Path Env:\'
 
     - task: PowerShell@1
       #condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))
       #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['TriggerBranch']))
       displayName: 'Apply Version To Application'
       inputs:
           scriptName: devops/misc-scripts/ApplyVersionToAssemblies.ps1

     - bash: |
        if [ "$(Build.Reason)" == "IndividualCI" ]; then
            echo "Disable tests"
            echo "##vso[task.setvariable variable=run_tests]false"
        else
            echo "Run tests"
            echo "##vso[task.setvariable variable=run_tests]true"
        fi
       displayName: set run_tests variable

     - template: 'pipeline\templates\restore-build-test-msbuild7.yml@devops'
       parameters: 
          repo: '$(Repo)'
          projectsolution: '$(ProjectSolution)'
          buildConfiguration: '$(BuildConfiguration)'
          buildplatform: '$(BuildPlatform)'
          vstsfeed: '$(VstsFeed)'
          adoproject: '$(AdoProject)'

     - powershell: |
            $ProjectPath='$(Repo)\Code\$(VsProjectNamePrefix)\$(VsProjectNamePrefix).csproj'
            Write-host "ProjectPath="$ProjectPath
            Write-Host "##vso[task.setvariable variable=ProjectPath;]$ProjectPath"

            $PublishPath='$(System.DefaultWorkingDirectory)\$(Repo)\Code\$(VsProjectNamePrefix)\publish'
            Write-host "PublishPath="$PublishPath
            Write-Host "##vso[task.setvariable variable=PublishPath;]$PublishPath"
       #condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))
       displayName: "Set/Print project/publish paths"

     - task: DotNetCoreCLI@2
       
       #condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['TriggerBranch']))
       inputs:
         command: 'publish'
         publishWebProjects: false
         projects: $(ProjectPath)
         arguments: '--no-build -c $(BuildConfiguration) -o $(PublishPath)'
         zipAfterPublish: false 
         modifyOutputPath: false
       displayName: Publish $(VsProjectNamePrefix)
         
     - powershell: |
          $temp = "$(ImageName)"
          $temp = $temp.ToLower()
          Write-host "image name="$(ImageName)
          Write-Host "##vso[task.setvariable variable=ImageNameLowercase;]$temp"
       displayName: 'Set image name'
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))
     
     #- task: DownloadPipelineArtifact@2
       #condition: and(succeeded(), ne(variables['Build.SourceBranchName'], variables['TriggerBranch']))
      # displayName: 'Download Pipeline Artifact'
      # inputs:
        #buildType: specific
        #project: '0b214fa2-b3b1-42b0-b0e3-ab1d83cc701f'
       # definition: 486
       # allowPartiallySucceededBuilds: true
       # artifactName: drop
        #targetPath: '$(PublishPath)'
       # condition: and(succeeded(), ne(variables['Build.SourceBranchName'], variables['TriggerBranch']))

     - powershell: |
          docker images --format='{{json .}}'|Select-String -Pattern "$(ImageNameLowercase)" |   ConvertFrom-Json |  ForEach-Object -process { docker rmi -f $_.ID}
       displayName: Remove previous docker images
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))

     - task: Docker@2
       displayName: Build docker image 
       inputs:
          command: build
          Dockerfile:  $(DockerFile)
          buildContext: $(System.DefaultWorkingDirectory)\$(Repo)\Code\$(VsProjectNamePrefix)
          arguments: "-t $(ImageNameLowercase)"
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))
   
     - bash: |
              acrname='acr$(env)$(AppPlatform)global'
              echo 'target acr name' $acrname
              echo "##vso[task.setvariable variable=acrname]$acrname"
       displayName: 'Set acr name'
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))

     - powershell: |
            $buildnumber_postfix=""
            $buildnumber = $Env:BUILD_BUILDNUMBER
            #write-host "buildnumber_postfix="$buildnumber_postfix 
            $tempString=$buildnumber.split("_")
            $buildnumber_postfix = $tempString[1]
            
            if($buildnumber_postfix)
            {
            write-host "buildnumber_postfix="$buildnumber_postfix 
            Write-Host "##vso[task.setvariable variable=buildnumber_postfix;]$buildnumber_postfix"
            
            }
            else
            {
            Throw("buildnumber_postfix variable is empty")
            }
       displayName: "set/print buildnumber_postfix"
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))

     - powershell: |
            $tag =""
            $buildnumber = $Env:BUILD_BUILDNUMBER
            $tempString=$buildnumber.split("_")
            $tag = $tempString[2]

            write-host "tag="$tag
            Write-Host "##vso[task.setvariable variable=tag;]$tag"
       displayName: "Set/Print Tag"
       condition: and(succeeded(),  ne(variables['Build.Reason'], 'PullRequest'))

     
     