trigger:
- api-tests
 
# variables:
  #system.debug: true
  #disable.coverage.autogenerate: true

pool:
  vmImage: 'ubuntu-latest'
 
steps:

- script: >-
    echo "##vso[task.prependpath]$HOME/.dotnet/tools"

- script: >-
    dotnet tool install -g dotnet-reportgenerator-globaltool

- script: >-
    sh Code/codecoverage.sh 'Code/Avalanche.Api.Tests/Avalanche.Api.Tests.csproj' 'release' '$(Agent.TempDirectory)/TestResults/api'

- script: >-
    sh Code/codecoverage.sh 'Code/Avalanche.Security.Server.Tests/Avalanche.Security.Server.Tests.csproj' 'release' '$(Agent.TempDirectory)/TestResults/security'

- bash: >-
    reportgenerator "-reports:$(Agent.TempDirectory)/TestResults/*.xml" "-targetdir:TestResults1" -reporttypes:xml

- script: >-
    ls $(Agent.TempDirectory)/TestResults