trigger:
- api-tests
 
# variables:
  #system.debug: true
  #disable.coverage.autogenerate: true

pool:
  vmImage: 'ubuntu-latest'
 
steps:

- script: >-
    ls .
- script: >-
    sh ../Code/codecoverage.sh 'Avalanche.Api.Tests/Avalanche.Api.Tests.csproj' 'release' '../TestResults/api'
    sh ../Code/codecoverage.sh 'Avalanche.Security.Server.Tests/Avalanche.Security.Server.Tests.csproj' 'release' '../TestResults/security'