name: $(BuildNumberPrefix)-$(MajorVersion).$(MinorVersion).$(Patch).$(ReleaseStage)_$(MajorVersion).$(MinorVersion).$(Date:yyMM).$(Date:dd)$(Rev:rr)_$(Date:yyyyMMdd)T$(Date:hhmmss)

trigger:
  - none
  
resources:
  repositories:
  - repository: devops
    type: git
    name: devops
    ref: pipeline-docker-update

#pool:
  #vmImage: $(PoolVmImage)

pool: $(pool)

variables:
  
  - group: 'vg-dev-avalanche-storage'
  
  #- name: System.Debug
    #value: true
  
stages:

# stage for creating PR comments if nuget pkgs verssion are not up to date
- template: pipeline\templates\nuget-version-check.yml@devops

- stage: build

  jobs:

  - job: build_test_publish
    steps:
     
     - checkout: self
     - checkout: devops

     - task: PowerShell@2
       displayName: List environmental variables
       inputs:
        targetType: 'inline'
        script: 'Get-ChildItem -Path Env:\'

     - template: 'pipeline\templates\restore-build-test-msbuild7.yml@devops'
       parameters: 
          repo: '$(Repo)'
          projectsolution: '$(ProjectSolution)'
          buildConfiguration: '$(BuildConfiguration)'
          buildplatform: '$(BuildPlatform)'
          vstsfeed: '$(VstsFeed)'
          adoproject: '$(AdoProject)'
          sonarprojectkey: '$(SonarProjectKey)'
          sonarprojetname: '$(SonarProjectKey)'

       