name: $(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - none

resources:
  repositories:
  
  - repository: avalanche-api
    type: git
    name: avalanche/avalanche-api
    ref: dev

  - repository: devops
    type: git
    name: avalanche/devops

pool:
  vmImage: 'ubuntu-latest'

variables:

  - template: pipeline-bug-workaround.yml
  - name: BuildConfiguration
    value: 'Release'

stages:
- stage: build
  jobs:
  - job: build_test_publish
    steps:

     - task: UseDotNet@2
       displayName: 'use dotnet 3.1.x'
       inputs:
        version: '3.1.x'
        packageType: runtime
        
     - task: UseDotNet@2
       displayName: 'use dotnet 2.2.x'
       inputs:
        version: '2.2.x'
        packageType: runtime
     
     - task: DotNetCoreCLI@2
       displayName: 'Restore Avalanche.Api'
       inputs:
        command: restore
        projects: '**/Code/Avalanche.Security.Server/Avalanche.Security.Server.csproj'
        vstsFeed: 'd61e3552-9162-4b94-9184-b843c159ef58'
    
     - task: DotNetCoreCLI@2
       displayName: 'Build Avalanche.Api'
       inputs:
        projects: '**/Code/Avalanche.Security.Server/Avalanche.Security.Server.csproj'
        arguments: '--configuration $(BuildConfiguration)'
     
     