CREATE TABLE "Users" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Users" PRIMARY KEY AUTOINCREMENT,
    "FirstName" TEXT COLLATE NOCASE NOT NULL,
    "LastName" TEXT COLLATE NOCASE NOT NULL,
    "UserName" TEXT COLLATE NOCASE NOT NULL,
    "Password" TEXT COLLATE NOCASE NOT NULL,
    UNIQUE("UserName")
);

CREATE UNIQUE INDEX "IX_Users_FirstName" ON "Users" ("FirstName");
