version: '3.4'

networks:
   app_net:
     external: true

services:
  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    container_name: stateserver-rabbitmq
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
        RABBITMQ_MNESIA_DIR: "/var/lib/rabbitmq/mnesia"
    ports:
    - "15672:15672"
    - "5672:5672"
    networks:
      app_net:
        ipv4_address: 192.168.1.65
    volumes:
    - type: bind
      source: C:\RabbitMQStateServer
      target: /var/lib/rabbitmq/mnesia
      read_only: false
      
  avalanche.api:
    container_name: avalancheapi
    image: ${DOCKER_REGISTRY-}avalancheapi     
    restart: always
    build:
      context: .
      dockerfile: Avalanche.Api/Dockerfile
    volumes:
    - type: bind
      source: C:\Olympus\AvalancheLogs
      target: /logs
      read_only: false
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\certificates
      target: /certificates
      read_only: true
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\apps\config\AvalancheApi
      target: /config
      read_only: false
      volume:
        nocopy: true
    networks:
      app_net:
        ipv4_address: 192.168.1.60
    environment:
      hostIpAddress: '10.0.75.1'
      WebRTCGrpcPort: '8001'
      PgsTimeoutGrpcPort: '8002'
      grpcCertificate: '/certificates/grpc_localhost_root_l1.pfx' 
      grpcPassword: '0123456789'
      seqUrl: 'http://seq:5341'
      logging:loglevel:default: 'debug'
      loggerFileName: 'avalancheapilogs.txt'
      loggerFolder: '/logs'
      loggerFileSizeLimit: 209715200
      loggerRetainedFileCountLimit: 5
    depends_on:
      - seqserver
      - rabbitmq
      - avalanche.security.server
  avalanche.security.server:
    container_name: avalanchesecurityserver
    image: ${DOCKER_REGISTRY-}avalanchesecurityserver
    build:
      context: .
      dockerfile: Avalanche.Security.Server/Dockerfile  
    restart: always
    volumes:
    - type: bind
      source: C:\Olympus\dbs
      target: /data
      read_only: false
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\certificates
      target: /certificates
      read_only: true
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\AvalancheLogs
      target: /logs
      read_only: false
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\apps\config\AvalancheApi
      target: /config
      read_only: false
      volume:
        nocopy: true
    networks:
      app_net:
        ipv4_address: 192.168.1.62
    environment:
      seqUrl: 'http://seq:5341'
      logging:loglevel:default: 'debug'
      loggerFileName: 'avalanchesecurityserverlogs.txt'
      loggerFolder: '/logs'
      loggerFileSizeLimit: 209715200
      loggerRetainedFileCountLimit: 5
    depends_on:
      - seqserver
  seqserver:
    container_name: seq
    image: 'datalust/seq:latest'
    ports:
      - '5341:80'
    networks:
        app_net:
            ipv4_address: 192.168.1.61
    environment:
      ACCEPT_EULA: 'Y'
    volumes:
      - type: volume
        source: seq_data
        target: /data

volumes:
    seq_data:

