version: '3.4'

services:
  avalanche.api:
    container_name: avalancheapi
    image: ${DOCKER_REGISTRY-}avalancheapi
    restart: always
    build:
      context: .
      dockerfile: Avalanche.Api/Dockerfile
    volumes:
    - type: bind
      source: C:\Olympus\AvalancheLogs
      target: /logs
      read_only: false
      volume:
        nocopy: true
    - type: bind
      source: C:\Olympus\apps\config\AvalancheApi
      target: /config
      read_only: false
      volume:
        nocopy: true
    environment:
      seqUrl: 'http://seq:5341'
      logging:loglevel:default: 'debug'

  seqserver:
    container_name: seq
    image: 'datalust/seq:latest'
    ports:
      - '5341:80'
    environment:
      ACCEPT_EULA: 'Y'
    volumes:
      - type: volume
        source: seq_data
        target: /data

volumes:
    seq_data:
