using System.Collections.Generic;
using Newtonsoft.Json;

namespace Avalanche.Api.ViewModels
{
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public class DynamicPropertyViewModel : DynamicBaseSettingViewModel
    {
        public bool IsAutoGenerated { get; set; }
        public bool IsHidden { get; set; }
        public List<string>? ComposedColumns { get; set; }

        public string? JsonKeyToShowFromRelatedObject { get; set; }
        public string? JsonKeyForRelatedObject { get; set; }
    }
}
