using Avalanche.Shared.Infrastructure.Enumerations;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Dynamic;

namespace Avalanche.Api.ViewModels
{
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public class DynamicPropertyViewModel : DynamicBaseSettingViewModel
    {
        public bool IsAutoGenerated { get; set; }
        public bool IsHidden { get; set; }

        public string JsonKeyToShowFromRelatedObject { get; set; }
        public string JsonKeyForRelatedObject { get; set; }
    }
}
