// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4, iterations: "1000", insecureSkipTLSVerify: true };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Genders",
    id: "7cb04431-cb45-4a2a-bc73-28e9477f1a38",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Metadata/genders",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Is an array", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData).to.be.an("array");
      });
    }
  });

  postman[Request]({
    name: "Get Procedure Types",
    id: "25e87952-8128-40d1-82c3-c5c99cc5f9cc",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Metadata/proceduretypes",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Is an array", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData).to.be.an("array");
      });
    }
  });

  postman[Request]({
    name: "Register Patient",
    id: "2adaa249-08ed-4f8a-bec4-807e9eb4df6f",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients",
    data:
      '{\r\n  "id": "string",\r\n  "name": "testing",\r\n  "lastName": "testing",\r\n  "dateOfBirth": "2020-02-13T15:04:32.364Z",\r\n  "gender": "string"\r\n}',
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "content-type": "application/json",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Successful POST request", function() {
        pm.expect(pm.response.code).to.be.oneOf([201, 202]);
      });
      pm.test("Patient was created", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.name).to.eql("testing");
        pm.expect(jsonData.lastName).to.eql("testing");
        pm.expect(jsonData).to.have.property("id");
        pm.expect(jsonData).to.have.property("name");
        pm.expect(jsonData).to.have.property("lastName");
        pm.expect(jsonData).to.have.property("department");
        pm.expect(jsonData).to.have.property("gender");
      });
    }
  });

  postman[Request]({
    name: "Quick Patient Registration",
    id: "cda1cb22-e353-4f61-aa4e-615699be8536",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients/quick",
    headers: {
      authority: "192.168.1.60:443",
      "content-length": "0",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Successful POST request", function() {
        pm.expect(pm.response.code).to.be.oneOf([201, 202]);
      });
    }
  });

  postman[Request]({
    name: "Search Patients",
    id: "3fd0ec9a-d39a-4dc8-81a8-d61f5b4ace96",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients/filtered",
    data: '{\r\n  "term": "string",\r\n  "page": 0,\r\n  "limit": 10\r\n}',
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "content-type": "application/json",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Contains data for paging", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData).to.have.a.property("items");
        pm.expect(jsonData).to.have.a.property("nextPage");
        pm.expect(jsonData).to.have.a.property("previousPage");
      });
    }
  });

  postman[Request]({
    name: "Get Physicians",
    id: "ee8bbe4e-b116-4660-bee9-bdcf8b695fb5",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Physicians",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      pm.test("Is an array", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData).to.be.an("array");
      });
    }
  });
}
