// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4, iterations: "1000", insecureSkipTLSVerify: true };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Genders",
    id: "58cccf1d-2122-4a7e-87c3-52774c2dc115",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Metadata/genders",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Get Procedure Types",
    id: "841bee18-17c8-4d25-b4fd-211f9e969e6a",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Metadata/proceduretypes",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Register Patient",
    id: "6208e6ca-7204-4dd1-bc0a-db0ed353d520",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients",
    data:
      '{\r\n  "id": "string",\r\n  "name": "testing",\r\n  "lastName": "testing",\r\n  "dateOfBirth": "2020-02-13T15:04:32.364Z",\r\n  "gender": "string"\r\n}',
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "content-type": "application/json",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Successful POST request", function() {
        pm.expect(pm.response.code).to.be.oneOf([201, 202]);
      });
      pm.test("Patient was created", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.name).to.eql("testing");
        pm.expect(jsonData.lastName).to.eql("testing");
      });
    }
  });

  postman[Request]({
    name: "Quick Patient Registration",
    id: "08f39b68-7352-4ec6-b4f6-afca104ed267",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients/quick",
    headers: {
      authority: "192.168.1.60:443",
      "content-length": "0",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Successful POST request", function() {
        pm.expect(pm.response.code).to.be.oneOf([201, 202]);
      });
    }
  });

  postman[Request]({
    name: "Search Patients",
    id: "20fe52c5-98d6-44b1-89ac-1b0ca546553e",
    method: "POST",
    address: "https://192.168.1.60:443/api/v1/Patients/filtered",
    data: '{\r\n  "term": "string",\r\n  "page": 0,\r\n  "limit": 10\r\n}',
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "content-type": "application/json",
      origin: "https://192.168.1.60:443",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Get Physicians",
    id: "4a3296b1-274a-41a8-a689-85fb7c36f98a",
    method: "GET",
    address: "https://192.168.1.60:443/api/v1/Physicians",
    headers: {
      authority: "192.168.1.60:443",
      accept: "text/plain",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
      "sec-fetch-site": "same-origin",
      "sec-fetch-mode": "cors",
      referer: "https://192.168.1.60:443/index.html",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
