using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using AutoMapper;
using Avalanche.Api.Managers.Data;
using Avalanche.Api.Services.Health;
using Avalanche.Api.Services.Maintenance;
using Avalanche.Api.Services.Media;
using Avalanche.Api.Services.Printing;
using Avalanche.Api.ViewModels;
using Avalanche.Shared.Infrastructure.Configuration;
using Avalanche.Shared.Infrastructure.Extensions;
using Ism.Common.Core.Configuration.Models;
using Microsoft.AspNetCore.Http;

namespace Avalanche.Api.Managers.Maintenance
{
    public class DeviceMaintenanceManager : MaintenanceManager
    {
        private readonly IStorageService _storageService;
        private readonly ConfigurationContext _configurationContext;

        private readonly IDeviceConfigurationManager _deviceConfigurationManager;

        public DeviceMaintenanceManager(IStorageService storageService,
            IDataManager dataManager, IMapper mapper,
            IHttpContextAccessor httpContextAccessor,
            ILibraryService libraryService,
            IFilesService filesService,
            IPrintingService printingService,
            ISharedConfigurationManager sharedConfigurationManager,
            IDeviceConfigurationManager deviceConfigurationManager) : base(storageService, dataManager, mapper, httpContextAccessor, libraryService, filesService, printingService, sharedConfigurationManager)
        {
            _deviceConfigurationManager = deviceConfigurationManager;
        }

        protected override async Task SaveEmbeddedList(string settingsKey, string jsonKey, string json, string schema = null)
        {
            if (string.IsNullOrEmpty(schema) || await _storageService.ValidateSchema(schema, json, 1, _configurationContext))
            {
                await _storageService.UpdateJsonProperty(settingsKey, jsonKey, json, 1, _configurationContext, true);

                switch (settingsKey)
                {
                    case "SetupConfiguration":
                        _deviceConfigurationManager.UpdatePatientInfo(json.Get<List<PatientInfoSetupConfiguration>>());
                        break;
                }
            }
            else
            {
                throw new ValidationException("Json Schema Invalid for " + jsonKey);
            }
        }

        protected override void CheckLinks(DynamicListViewModel category)
        {
            switch (category.SourceKey)
            {
                case "ProcedureTypes":
                    for (int i = 0; i < category.Links.Count; i++)
                    {
                        var link = category.Links[i];
                        switch (link.Key)
                        {
                            case "AutoLabels":
                                if (!_deviceConfigurationManager.GetLabelsConfigurationSettings().AutoLabelsEnabled)
                                {
                                    category.Links.Remove(link);
                                }
                                break;
                            default:
                                break;
                        }
                    }
                    break;
                default:
                    break;
            }
        }

        protected override async Task SetIsRequired(string key, DynamicPropertyViewModel item)
        {
            //It is a switch because this can grow on time
            switch (key)
            {
                case "DepartmentsMetadata":
                    switch (item.JsonKey)
                    {
                        case "DepartmentId":
                            bool departmentsSupported = _deviceConfigurationManager.GetSetupConfigurationSettings().General.DepartmentsSupported;

                            item.Required = departmentsSupported;
                            item.IsHidden = !departmentsSupported;
                            item.IsAutoGenerated = !departmentsSupported;

                            break;
                    }
                    break;
            }
        }
    }
}
